services:
  db:
    image: postgres:15
    container_name: safesign_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: safesign_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: safesign_api
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: node server.js  # <--- Forçar a execução direta do ficheiro
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_USER=user_admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=safesign_db
      - POSTGRES_PORT=5432
      - PORT=5000